.PHONY: import_streams

import_streams:
	rai imports:stream --source RECOMMENDATION_DEMO.PUBLIC.TRAIN --model recommendation_demo
	rai imports:stream --source RECOMMENDATION_DEMO.PUBLIC.TEST --model recommendation_demo
	rai imports:stream --source RECOMMENDATION_DEMO.PUBLIC.MOVIE_DETAILS --model recommendation_demo